theme: jekyll-theme-slate
markdown: kramdown
# Site settings
title: Shell's Farm                    # 你的博客网站标题
SEOTitle: Shell's Farm		# SEO 标题
description: "No matter.  Fail better. "	   	   # 随便说点，描述一下
email: yunzhenyao at 126 dot com
url: "https://shellyyz.github.io"

# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "No matter.  Fail better. "
#sidebar-avatar: /img/avatar-by.JPG

# SNS settings
github_username: shellyyz     # 你的github账号

# Build settings
paginate: 10              # 一页你准备放几篇文
