# Permalinks
permalink:           pretty

# Setup
title:               Brianne's Farm
tagline:             La La La ~
url:                 http://shellyyz.github.io
baseurl:             "http://shellyyz.github.io"
analytics_id:

# Owner/author information
owner:
  name:           Brianne Yao
  avatar:         avatar.png
  bio:            "Designer."
  email:          yunzhenyao@126.com
  twitter:        shellyyz
  github:         shellyyz
  instagram:      shellyyz
  dribbble:       shellyyz

# Custom vars
version:             2.0.0
github:
  repo:

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Gems
gems:
  - jekyll-paginate
