# Permalinks
permalink:           pretty

# Setup
title:               Progress
tagline:             A responsive blog theme that illustrates reading progress. Suited for continous reading.
url:                 http://shellyyz.github.io
baseurl:             ""
analytics_id:

# Owner/author information
owner:
  name:           Brianne Yao
  avatar:         avatar.png
  bio:            "Designer."
  email:          yunzhenyao@126.com
  twitter:        shellyyz
  github:         shellyyz
  instagram:      shellyyz
  dribbble:       shellyyz
    location:       "Shanghai, CN"


# Custom vars
version:             2.0.0
github:
  repo:

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Gems
gems:
  - jekyll-paginate
